name: Version Increment

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.name 'Chris'
      - run: git config --global user.email 'hendecasyllabic@googlemail.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
